# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_submitparamter'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitparamter',
            name='res_chain',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submitparamter',
            name='res_ligand_chain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitparamter',
            name='res_ligand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
