# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181108_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitparamter',
            name='protein_renumber_file',
            field=models.FileField(blank=True, null=True, upload_to='protein_file/'),
        ),
    ]
