# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_submitparamter_protein_renumber_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitparamter',
            name='inputs_pos_file',
            field=models.FileField(blank=True, null=True, upload_to='inputs_pos_file/'),
        ),
        migrations.AddField(
            model_name='submitparamter',
            name='ligand_params_file',
            field=models.FileField(blank=True, null=True, upload_to='ligand_file/'),
        ),
    ]
