# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181109_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitparamter',
            name='inputs_pos_file',
            field=models.FileField(blank=True, null=True, upload_to='inputs_pos_files/'),
        ),
        migrations.AlterField(
            model_name='submitparamter',
            name='ligand_file',
            field=models.FileField(blank=True, null=True, upload_to='ligand_files/'),
        ),
        migrations.AlterField(
            model_name='submitparamter',
            name='ligand_params_file',
            field=models.FileField(blank=True, null=True, upload_to='ligand_params_files/'),
        ),
        migrations.AlterField(
            model_name='submitparamter',
            name='protein_file',
            field=models.FileField(blank=True, null=True, upload_to='protein_files/'),
        ),
        migrations.AlterField(
            model_name='submitparamter',
            name='protein_renumber_file',
            field=models.FileField(blank=True, null=True, upload_to='protein_files/'),
        ),
    ]
