# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0007_auto_20181109_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invited_reason', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitParamter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('protein_file', models.FileField(blank=True, null=True, upload_to='protein_files/')),
                ('protein_renumber_file', models.FileField(blank=True, null=True, upload_to='protein_files/')),
                ('ligand_file', models.FileField(blank=True, null=True, upload_to='ligand_files/')),
                ('other_ligands', models.CharField(blank=True, max_length=1000, null=True)),
                ('res_chain', models.CharField(blank=True, max_length=20, null=True)),
                ('res_ligand_chain', models.CharField(blank=True, max_length=50, null=True)),
                ('res_ligand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ligand_params_file', models.FileField(blank=True, null=True, upload_to='ligand_params_files/')),
                ('inputs_pos_file', models.FileField(blank=True, null=True, upload_to='inputs_pos_files/')),
                ('constrain_info', models.CharField(blank=True, max_length=20000, null=True)),
                ('cat_ID', models.CharField(blank=True, max_length=1000, null=True)),
                ('cst_file', models.FileField(blank=True, null=True, upload_to='cst_files/')),
                ('design_mini_range', models.CharField(blank=True, max_length=1000, null=True)),
                ('design_cst', models.FileField(blank=True, null=True, upload_to='design_cst_files/')),
                ('analysis_param', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='polls.Membership', to='polls.Person'),
        ),
    ]
