# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20181109_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitparamter',
            name='match_cst_file',
            field=models.FileField(blank=True, null=True, upload_to='match_cst_files/'),
        ),
    ]
