# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_submitparamter_match_cst_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitparamter',
            old_name='cst_file',
            new_name='user_defined_cst_file',
        ),
    ]
