# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20181109_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitparamter',
            name='user_defined_cst_file',
            field=models.FileField(blank=True, null=True, upload_to='user_defined_cst_files/'),
        ),
    ]
