# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_submitparamter_um_pdbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitparamter',
            name='UM_pdbs',
        ),
    ]
