# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_submitparamter_design_ligand_name_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitparamter',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
