# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_submitparamter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitparamter',
            name='UM_pdb_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
